sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  # Spectron specific configs
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
- npm run test
- npm run test:electron

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    npm ship:windows && npm ship:mac && npm ship:linux && npm ship:linux:arm

notifications:
  email:
    on_success: change
    on_failure: change