sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
- npm run test
- npm run build