osx_image: xcode8.4

dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js: "8"

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  chrome: stable # have Travis install chrome stable.

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - yarn

script:
- echo "Unit Tests"
- xvfb-run yarn test

- echo "E2E Tests"
- xvfb-run yarn test:electron

- echo "Deploy linux version to GitHub"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi

- echo "Deploy windows version to GitHub"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:win; fi

- echo "Deploy mac version to GitHub"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:mac; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine